using System.ComponentModel;

namespace ConsoleApplication1
{
    partial class MainWindow
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.P1 = new System.Windows.Forms.TextBox();
            this.P2 = new System.Windows.Forms.TextBox();
            this.P3 = new System.Windows.Forms.TextBox();
            this.C3 = new System.Windows.Forms.TextBox();
            this.C1 = new System.Windows.Forms.TextBox();
            this.C4 = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.C2 = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.button1 = new System.Windows.Forms.Button();
            this.@out = new System.Windows.Forms.RichTextBox();
            this.P1C2 = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.P1C3 = new System.Windows.Forms.TextBox();
            this.P1C1 = new System.Windows.Forms.TextBox();
            this.P1C4 = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.P2C2 = new System.Windows.Forms.TextBox();
            this.P2C3 = new System.Windows.Forms.TextBox();
            this.P2C1 = new System.Windows.Forms.TextBox();
            this.P2C4 = new System.Windows.Forms.TextBox();
            this.P3C2 = new System.Windows.Forms.TextBox();
            this.P3C3 = new System.Windows.Forms.TextBox();
            this.P3C1 = new System.Windows.Forms.TextBox();
            this.P3C4 = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            this.label1.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.label1.Location = new System.Drawing.Point(12, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(45, 23);
            this.label1.TabIndex = 0;
            this.label1.Text = "P1:";
            this.label2.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.label2.Location = new System.Drawing.Point(12, 32);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(45, 23);
            this.label2.TabIndex = 1;
            this.label2.Text = "P2:";
            this.label3.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.label3.Location = new System.Drawing.Point(12, 55);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(45, 23);
            this.label3.TabIndex = 2;
            this.label3.Text = "P3:";
            this.P1.Location = new System.Drawing.Point(64, 9);
            this.P1.Name = "P1";
            this.P1.Size = new System.Drawing.Size(100, 23);
            this.P1.TabIndex = 3;
            this.P1.Text = "67";
            this.P2.Location = new System.Drawing.Point(64, 32);
            this.P2.Name = "P2";
            this.P2.Size = new System.Drawing.Size(100, 23);
            this.P2.TabIndex = 4;
            this.P2.Text = "54";
            this.P3.Location = new System.Drawing.Point(64, 55);
            this.P3.Name = "P3";
            this.P3.Size = new System.Drawing.Size(100, 23);
            this.P3.TabIndex = 5;
            this.P3.Text = "69";
            this.C3.Location = new System.Drawing.Point(237, 55);
            this.C3.Name = "C3";
            this.C3.Size = new System.Drawing.Size(100, 23);
            this.C3.TabIndex = 11;
            this.C3.Text = "45";
            this.C1.Location = new System.Drawing.Point(237, 9);
            this.C1.Name = "C1";
            this.C1.Size = new System.Drawing.Size(100, 23);
            this.C1.TabIndex = 10;
            this.C1.Text = "38";
            this.C4.Location = new System.Drawing.Point(237, 78);
            this.C4.Name = "C4";
            this.C4.Size = new System.Drawing.Size(100, 23);
            this.C4.TabIndex = 9;
            this.C4.Text = "42";
            this.label4.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.label4.Location = new System.Drawing.Point(187, 32);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(45, 23);
            this.label4.TabIndex = 8;
            this.label4.Text = "C2:";
            this.label5.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.label5.Location = new System.Drawing.Point(187, 55);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(45, 23);
            this.label5.TabIndex = 7;
            this.label5.Text = "C3:";
            this.label6.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.label6.Location = new System.Drawing.Point(187, 9);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(45, 23);
            this.label6.TabIndex = 6;
            this.label6.Text = "C1:";
            this.C2.Location = new System.Drawing.Point(237, 32);
            this.C2.Name = "C2";
            this.C2.Size = new System.Drawing.Size(100, 23);
            this.C2.TabIndex = 13;
            this.C2.Text = "60";
            this.label7.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.label7.Location = new System.Drawing.Point(187, 78);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(45, 23);
            this.label7.TabIndex = 12;
            this.label7.Text = "C4:";
            this.button1.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.button1.Location = new System.Drawing.Point(360, 9);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(112, 91);
            this.button1.TabIndex = 15;
            this.button1.Text = "Calculate";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.@out.Location = new System.Drawing.Point(12, 135);
            this.@out.Name = "out";
            this.@out.Size = new System.Drawing.Size(909, 372);
            this.@out.TabIndex = 16;
            this.@out.Text = "";
            this.P1C2.Location = new System.Drawing.Point(569, 32);
            this.P1C2.Name = "P1C2";
            this.P1C2.Size = new System.Drawing.Size(65, 23);
            this.P1C2.TabIndex = 24;
            this.P1C2.Text = "11";
            this.label8.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label8.Location = new System.Drawing.Point(496, 78);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(66, 23);
            this.label8.TabIndex = 23;
            this.label8.Text = "P1->C4:";
            this.P1C3.Location = new System.Drawing.Point(569, 55);
            this.P1C3.Name = "P1C3";
            this.P1C3.Size = new System.Drawing.Size(65, 23);
            this.P1C3.TabIndex = 22;
            this.P1C3.Text = "9";
            this.P1C1.Location = new System.Drawing.Point(569, 9);
            this.P1C1.Name = "P1C1";
            this.P1C1.Size = new System.Drawing.Size(65, 23);
            this.P1C1.TabIndex = 21;
            this.P1C1.Text = "10";
            this.P1C4.Location = new System.Drawing.Point(569, 78);
            this.P1C4.Name = "P1C4";
            this.P1C4.Size = new System.Drawing.Size(65, 23);
            this.P1C4.TabIndex = 20;
            this.P1C4.Text = "13";
            this.label9.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label9.Location = new System.Drawing.Point(496, 32);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(66, 23);
            this.label9.TabIndex = 19;
            this.label9.Text = "P1->C2:";
            this.label10.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label10.Location = new System.Drawing.Point(496, 55);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(66, 23);
            this.label10.TabIndex = 18;
            this.label10.Text = "P1->C3:";
            this.label11.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label11.Location = new System.Drawing.Point(496, 9);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(66, 23);
            this.label11.TabIndex = 17;
            this.label11.Text = "P1->C1:";
            this.P2C2.Location = new System.Drawing.Point(713, 32);
            this.P2C2.Name = "P2C2";
            this.P2C2.Size = new System.Drawing.Size(65, 23);
            this.P2C2.TabIndex = 32;
            this.P2C2.Text = "18";
            this.P2C3.Location = new System.Drawing.Point(713, 55);
            this.P2C3.Name = "P2C3";
            this.P2C3.Size = new System.Drawing.Size(65, 23);
            this.P2C3.TabIndex = 30;
            this.P2C3.Text = "20";
            this.P2C1.Location = new System.Drawing.Point(713, 9);
            this.P2C1.Name = "P2C1";
            this.P2C1.Size = new System.Drawing.Size(65, 23);
            this.P2C1.TabIndex = 29;
            this.P2C1.Text = "16";
            this.P2C4.Location = new System.Drawing.Point(713, 78);
            this.P2C4.Name = "P2C4";
            this.P2C4.Size = new System.Drawing.Size(65, 23);
            this.P2C4.TabIndex = 28;
            this.P2C4.Text = "20";
            this.P3C2.Location = new System.Drawing.Point(857, 32);
            this.P3C2.Name = "P3C2";
            this.P3C2.Size = new System.Drawing.Size(65, 23);
            this.P3C2.TabIndex = 40;
            this.P3C2.Text = "30";
            this.P3C3.Location = new System.Drawing.Point(857, 55);
            this.P3C3.Name = "P3C3";
            this.P3C3.Size = new System.Drawing.Size(65, 23);
            this.P3C3.TabIndex = 38;
            this.P3C3.Text = "28";
            this.P3C1.Location = new System.Drawing.Point(857, 9);
            this.P3C1.Name = "P3C1";
            this.P3C1.Size = new System.Drawing.Size(65, 23);
            this.P3C1.TabIndex = 37;
            this.P3C1.Text = "26";
            this.P3C4.Location = new System.Drawing.Point(857, 78);
            this.P3C4.Name = "P3C4";
            this.P3C4.Size = new System.Drawing.Size(65, 23);
            this.P3C4.TabIndex = 36;
            this.P3C4.Text = "35";
            this.label12.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label12.Location = new System.Drawing.Point(640, 76);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(66, 23);
            this.label12.TabIndex = 44;
            this.label12.Text = "P2->C4:";
            this.label13.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label13.Location = new System.Drawing.Point(640, 30);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(66, 23);
            this.label13.TabIndex = 43;
            this.label13.Text = "P2->C2:";
            this.label14.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label14.Location = new System.Drawing.Point(640, 53);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(66, 23);
            this.label14.TabIndex = 42;
            this.label14.Text = "P2->C3:";
            this.label15.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label15.Location = new System.Drawing.Point(640, 7);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(66, 23);
            this.label15.TabIndex = 41;
            this.label15.Text = "P2->C1:";
            this.label16.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label16.Location = new System.Drawing.Point(785, 78);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(66, 23);
            this.label16.TabIndex = 48;
            this.label16.Text = "P3->C4:";
            this.label17.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label17.Location = new System.Drawing.Point(785, 32);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(66, 23);
            this.label17.TabIndex = 47;
            this.label17.Text = "P3->C2:";
            this.label18.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label18.Location = new System.Drawing.Point(785, 55);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(66, 23);
            this.label18.TabIndex = 46;
            this.label18.Text = "P3->C3:";
            this.label19.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label19.Location = new System.Drawing.Point(785, 9);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(66, 23);
            this.label19.TabIndex = 45;
            this.label19.Text = "P3->C1:";
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(933, 519);
            this.Controls.Add(this.label16);
            this.Controls.Add(this.label17);
            this.Controls.Add(this.label18);
            this.Controls.Add(this.label19);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label15);
            this.Controls.Add(this.P3C2);
            this.Controls.Add(this.P3C3);
            this.Controls.Add(this.P3C1);
            this.Controls.Add(this.P3C4);
            this.Controls.Add(this.P2C2);
            this.Controls.Add(this.P2C3);
            this.Controls.Add(this.P2C1);
            this.Controls.Add(this.P2C4);
            this.Controls.Add(this.P1C2);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.P1C3);
            this.Controls.Add(this.P1C1);
            this.Controls.Add(this.P1C4);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.@out);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.C2);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.C3);
            this.Controls.Add(this.C1);
            this.Controls.Add(this.C4);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.P3);
            this.Controls.Add(this.P2);
            this.Controls.Add(this.P1);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Name = "MainWindow";
            this.Text = "MainWindow";
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox P1;
        private System.Windows.Forms.TextBox P2;
        private System.Windows.Forms.TextBox P3;
        private System.Windows.Forms.TextBox C3;
        private System.Windows.Forms.TextBox C1;
        private System.Windows.Forms.TextBox C4;
        private System.Windows.Forms.TextBox C2;
        private System.Windows.Forms.RichTextBox @out;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox P1C2;
        private System.Windows.Forms.TextBox P1C3;
        private System.Windows.Forms.TextBox P1C1;
        private System.Windows.Forms.TextBox P1C4;
        private System.Windows.Forms.TextBox P2C2;
        private System.Windows.Forms.TextBox P2C3;
        private System.Windows.Forms.TextBox P2C1;
        private System.Windows.Forms.TextBox P2C4;
        private System.Windows.Forms.TextBox P3C2;
        private System.Windows.Forms.TextBox P3C3;
        private System.Windows.Forms.TextBox P3C1;
        private System.Windows.Forms.TextBox P3C4;
    }
}